In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df_title = pd.read_csv('data/movie_title.csv')

In [3]:
df_review = pd.read_csv('data/movie_review.csv')

In [4]:
df_title

      item_id                                      title
0           1                           Toy Story (1995)
1           2                           GoldenEye (1995)
2           3                          Four Rooms (1995)
3           4                          Get Shorty (1995)
4           5                             Copycat (1995)
...       ...                                        ...
1677     1678                          Mat' i syn (1997)
1678     1679                           B. Monkey (1998)
1679     1680                       Sliding Doors (1998)
1680     1681                        You So Crazy (1994)
1681     1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [5]:
df_review

       user_id  item_id  rating  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

#### 두개의 데이터프레임을 하나로 합친다

In [11]:
df_movie = pd.merge(df_title, df_review, on= 'item_id', how='left')

In [42]:
df_movie.groupby('title')['rating'].mean().sort_values(ascending=False)

title
Aiqing wansui (1994)                                 5.0
Entertaining Angels: The Dorothy Day Story (1996)    5.0
Santa with Muscles (1996)                            5.0
Prefontaine (1997)                                   5.0
They Made Me a Criminal (1939)                       5.0
                                                    ...
Pharaoh's Army (1995)                                1.0
August (1996)                                        1.0
Babyfever (1994)                                     1.0
Amityville: A New Generation (1993)                  1.0
Woman in Question, The (1950)                        1.0
Name: rating, Length: 1664, dtype: float64

In [43]:
df_movie.groupby('title')['rating'].agg(['mean', 'count']).sort_values('mean', ascending=False)

                                                   mean  count
title
Aiqing wansui (1994)                                5.0      1
Entertaining Angels: The Dorothy Day Story (1996)   5.0      1
Santa with Muscles (1996)                           5.0      2
Prefontaine (1997)                                  5.0      3
They Made Me a Criminal (1939)                      5.0      1
...                                                 ...    ...
Pharaoh's Army (1995)                               1.0      1
August (1996)                                       1.0      1
Babyfever (1994)                                    1.0      2
Amityville: A New Generation (1993)                 1.0      5
Woman in Question, The (1950)                       1.0      1

[1664 rows x 2 columns]

In [18]:
df_movie.groupby('title')['rating'].describe().sort_values('count')

,count,mean,std,min,25%,50%,75%,max
title,,,,,,,,
Á köldum klaka (Cold Fever) (1994),1.0,3.000000,NaN,3.0,3.0,3.0,3.0,3.0
Yankee Zulu (1994),1.0,1.000000,NaN,1.0,1.0,1.0,1.0,1.0
Aiqing wansui (1994),1.0,5.000000,NaN,5.0,5.0,5.0,5.0,5.0
Window to Paris (1994),1.0,4.000000,NaN,4.0,4.0,4.0,4.0,4.0
Wings of Courage (1995),1.0,4.000000,NaN,4.0,4.0,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...
Liar Liar (1997),485.0,3.156701,1.098544,1.0,3.0,3.0,4.0,5.0
Return of the Jedi (1983),507.0,4.007890,0.923955,1.0,3.0,4.0,5.0,5.0
Fargo (1996),508.0,4.155512,0.975756,1.0,4.0,4.0,5.0,5.0
Contact (1997),509.0,3.803536,0.994427,1.0,3.0,4.0,5.0,5.0
Star Wars (1977),583.0,4.358491,0.881341,1.0,4.0,5.0,5.0,5.0

### 상관계수 => 유사도를 측정
### 추천 시스템 만들기 => 협업 필터링 기법
### 협업 필터링은, 유저 기반의 협업 필터링과 아이템 기반 협업 필터링이 있다.
#### 유저기반: 성향이 비슷한 유저를 찾아서 추천하는 것.
#### 아이템 기반: 아이템이 비슷한 것을 추천하는 것.

In [20]:
df_movie.corr(numeric_only=True)

            item_id   user_id    rating  timestamp
item_id    1.000000  0.010377 -0.189124   0.041867
user_id    0.010377  1.000000 -0.009371   0.019082
rating    -0.189124 -0.009371  1.000000  -0.012003
timestamp  0.041867  0.019082 -0.012003   1.000000

In [23]:
df = df_movie.pivot_table(columns='title', index='user_id', values='rating' )

In [24]:
df

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,2.0,5.0,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,5.0,3.0,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,NaN

# Titanic (1997)

In [28]:
df_movie.loc[df_movie['title'].str.contains('Tita'), ]

       item_id           title  user_id  rating  timestamp
48602      313  Titanic (1997)      240       5  885775604
48603      313  Titanic (1997)      134       5  891732150
48604      313  Titanic (1997)      319       5  889816026
48605      313  Titanic (1997)      111       4  891679901
48606      313  Titanic (1997)      236       4  890115777
...        ...             ...      ...     ...        ...
48947      313  Titanic (1997)      829       4  891204191
48948      313  Titanic (1997)      818       4  891870173
48949      313  Titanic (1997)      487       3  883439795
48950      313  Titanic (1997)      838       5  887060659
48951      313  Titanic (1997)      780       5  891362901

[350 rows x 5 columns]

In [29]:
# 이 영화와 비슷한 영화를 추천

In [32]:
df.corr()['Titanic (1997)'].sort_values(ascending=False).head(10)

title
Simple Wish, A (1997)                      1.0
Newton Boys, The (1998)                    1.0
Underworld (1997)                          1.0
Amazing Panda Adventure, The (1995)        1.0
Vermin (1998)                              1.0
Getting Even with Dad (1994)               1.0
Crossfire (1947)                           1.0
Dangerous Ground (1997)                    1.0
Wooden Man's Bride, The (Wu Kui) (1994)    1.0
For Ever Mozart (1996)                     1.0
Name: Titanic (1997), dtype: float64

In [33]:
df['Star Wars (1977)']

user_id
1      5.0
2      5.0
3      NaN
4      5.0
5      4.0
      ...
939    NaN
940    4.0
941    NaN
942    5.0
943    4.0
Name: Star Wars (1977), Length: 943, dtype: float64

In [39]:
df.corr(min_periods=50)['Titanic (1997)'].sort_values(ascending=False).head(10)

title
Titanic (1997)                       1.000000
River Wild, The (1994)               0.497600
Abyss, The (1989)                    0.472103
True Lies (1994)                     0.435104
Last of the Mohicans, The (1992)     0.427239
Die Hard (1988)                      0.403124
Air Force One (1997)                 0.383730
Jurassic Park (1993)                 0.382785
E.T. the Extra-Terrestrial (1982)    0.373201
Pretty Woman (1990)                  0.372027
Name: Titanic (1997), dtype: float64

In [41]:
df.corr(min_periods=50)['Star Wars (1977)'].sort_values(ascending=False).head(10)

title
Star Wars (1977)                                      1.000000
Empire Strikes Back, The (1980)                       0.747981
Return of the Jedi (1983)                             0.672556
Raiders of the Lost Ark (1981)                        0.536117
Austin Powers: International Man of Mystery (1997)    0.377433
Sting, The (1973)                                     0.367538
Indiana Jones and the Last Crusade (1989)             0.350107
Pinocchio (1940)                                      0.347868
Things to Do in Denver when You're Dead (1995)        0.337714
Shadowlands (1993)                                    0.332941
Name: Star Wars (1977), dtype: float64

### 해당 유저에 맞는 영화를 추천하는, 개인화 추천

In [44]:
# 예를 들어서, user_id 가 1인 사람

In [50]:
df_movie['user_id'].value_counts()

user_id
405    737
655    685
13     636
450    540
276    518
      ...
36      20
364     20
685     20
631     20
418     20
Name: count, Length: 943, dtype: int64

In [82]:
my_review.shape

(20, 3)

In [83]:
my_review.shape[0]

20

In [ ]:
pd.concat()

In [111]:
# 로그인 한 유저의 영화 별점 데이터를 가져온다.
my_review = df_movie.loc[df_movie['user_id'] == 100,['user_id', 'title', 'rating']].reset_index(drop=True)
# 비어있는 데이터프레임을 하나 만든다: 추천 영화 목록을 담는다.
movie_list = pd.DataFrame()
# 유저가 이미 본 영화들의 추천영화들을 싹 다 가져온다.
for index in range(0, my_review.shape[0]) :
    title = my_review['title'][index]
    df_recom = (df_corr[title].dropna().sort_values(ascending=False) * my_review['rating'][index]).to_frame()
    df_recom.columns = ['weight']
    df_recom.reset_index(inplace=True)
    movie_list = pd.concat([movie_list, df_recom])
    print(df_recom)
# 이미 본 영화는 제거
movie_list.set_index('title', inplace=True)
for title in my_review['title'] :
    if title in movie_list.index :
        movie_list.drop(title, inplace=True)
# 중복 영화는 weight 가 높은것으로 놔둔다.
movie_list = movie_list.groupby('title')['weight'].max()
# 최상위 10개만 가져온다.
movie_list.sort_values(ascending=False).head(10)

                                    title    weight
0                          Contact (1997)  4.000000
1                             Nell (1994)  2.196921
2              Spitfire Grill, The (1996)  2.114459
3                     Philadelphia (1993)  1.786038
4                        Mask, The (1994)  1.673311
..                                    ...       ...
405               Some Like It Hot (1959) -0.817603
406             Gone with the Wind (1939) -0.848489
407  Beautician and the Beast, The (1997) -0.867337
408                   First Knight (1995) -0.896389
409            Conan the Barbarian (1981) -0.931390

[410 rows x 2 columns]
Empty DataFrame
Columns: [title, weight]
Index: []
                            title    weight
0              Chasing Amy (1997)  3.000000
1         Frighteners, The (1996)  1.567830
2            Mars Attacks! (1996)  1.369201
3                  Kingpin (1996)  1.233913
4            Donnie Brasco (1997)  1.213528
..                            ...       ...
202               Clueless (1995) -0.383437
203                 Brazil (1985) -0.409362
204  To Kill a Mockingbird (1962) -0.491810
205           Shining, The (1980) -0.504802
206              Quiz Show (1994) -0.606461

[207 rows x 2 columns]
                                                 title    weight
0                               Full Monty, The (1997)  4.000000
1                               Cinema Paradiso (1988)  2.066119
2                                         Kolya (1996)  2.060019
3                                     Boot, Das (1981)  1.894972
4    Adventures of Priscilla, Queen of the Desert, ...  1.767058
..                                                 ...       ...
214                       2001: A Space Odyssey (1968) -0.597146
215                               Air Force One (1997) -0.606311
216                                  Saint, The (1997) -0.621692
217                                     Volcano (1997) -0.753965
218                                    Die Hard (1988) -1.140466

[219 rows x 2 columns]
                               title    weight
0                     Gattaca (1997)  3.000000
1                Men in Black (1997)  1.307132
2      Independence Day (ID4) (1996)  1.289526
3     Raiders of the Lost Ark (1981)  1.248552
4          Fifth Element, The (1997)  0.979305
5                   Toy Story (1995)  0.942110
6         Tomorrow Never Dies (1997)  0.909382
7                  Saint, The (1997)  0.891768
8        Seven Years in Tibet (1997)  0.889727
9          Return of the Jedi (1983)  0.877792
10                  Star Wars (1977)  0.849014
11          L.A. Confidential (1997)  0.736567
12                  Liar Liar (1997)  0.701394
13               Dante's Peak (1997)  0.671380
14              Jerry Maguire (1996)  0.629371
15                  G.I. Jane (1997)  0.600810
16                   Cop Land (1997)  0.588528
17                    Contact (1997)  0.584468
18   Star Trek: First Contact (1996)  0.533586
19          Conspiracy Theory (1997)  0.509122
20              Air Force One (1997)  0.492770
21                  Rock, The (1996)  0.479225
22                     Scream (1996)  0.478333
23             Twelve Monkeys (1995)  0.386934
24          Starship Troopers (1997)  0.367667
25                  Game, The (1997)  0.324986
26                   In & Out (1997)  0.324877
27             Rainmaker, The (1997)  0.308627
28            Full Monty, The (1997)  0.276365
29              Boogie Nights (1997)  0.263702
30                      Evita (1996)  0.239877
31                    Titanic (1997)  0.128142
32  Silence of the Lambs, The (1991)  0.022630
33                Chasing Amy (1997)  0.021996
34             Godfather, The (1972) -0.067956
35           Devil's Own, The (1997) -0.177923
36      Devil's Advocate, The (1997) -0.296923
37                Wag the Dog (1997) -0.360850
38                      Fargo (1996) -0.421112
39          Good Will Hunting (1997) -0.443772
40                    Amistad (1997) -0.485673
41               Pulp Fiction (1994) -0.572375
42       English Patient, The (1996) -0.776443
                                         title    weight
0                     Starship Troopers (1997)  3.000000
1                   Alien: Resurrection (1997)  1.771235
2                         Event Horizon (1997)  1.468745
3                              Scream 2 (1997)  1.276973
4                 Devil's Advocate, The (1997)  1.258664
..                                         ...       ...
157                       Fly Away Home (1996) -0.501570
158  Butch Cassidy and the Sundance Kid (1969) -0.609078
159     One Flew Over the Cuckoo's Nest (1975) -0.616732
160                       Graduate, The (1967) -0.646349
161                 Blues Brothers, The (1980) -0.667104

[162 rows x 2 columns]
                         title    weight
0     Good Will Hunting (1997)  4.000000
1                 Speed (1994)  2.371772
2         Seven (Se7en) (1995)  2.151834
3        Kiss the Girls (1997)  2.131876
4             Rock, The (1996)  1.921176
..                         ...       ...
113              Psycho (1960) -0.009589
114          Saint, The (1997) -0.077454
115             Gattaca (1997) -0.591696
116             Volcano (1997) -0.715252
117  Fifth Element, The (1997) -0.828649

[118 rows x 2 columns]
                                    title    weight
0             English Patient, The (1996)  3.000000
1               Angels and Insects (1995)  1.438444
2           Wings of the Dove, The (1997)  1.422472
3                       Unforgiven (1992)  1.376277
4                      Postino, Il (1994)  1.284967
..                                    ...       ...
346                  Jungle2Jungle (1997) -0.422055
347                     To Die For (1995) -0.502377
348       Sex, Lies, and Videotape (1989) -0.550406
349  Star Trek IV: The Voyage Home (1986) -0.688279
350                        Gattaca (1997) -0.776443

[351 rows x 2 columns]
                                      title    weight
0                             Scream (1996)  2.000000
1                           Scream 2 (1997)  1.412056
2    I Know What You Did Last Summer (1997)  1.173456
3                          Cape Fear (1962)  1.035136
4                               Wolf (1994)  1.003724
..                                      ...       ...
383               Lawrence of Arabia (1962) -0.381539
384               Gone with the Wind (1939) -0.383665
385    Bridge on the River Kwai, The (1957) -0.467957
386                          Amistad (1997) -0.543467
387              Spitfire Grill, The (1996) -0.583904

[388 rows x 2 columns]
                            title    weight
0                    Evita (1996)  3.000000
1          Peacemaker, The (1997)  1.346220
2                  Amistad (1997)  1.337009
3            Donnie Brasco (1997)  1.193628
4          River Wild, The (1994)  1.106714
..                            ...       ...
168        Raising Arizona (1987) -0.423705
169  2001: A Space Odyssey (1968) -0.428355
170    Clockwork Orange, A (1971) -0.433489
171       Mighty Aphrodite (1995) -0.501781
172             GoodFellas (1990) -0.590548

[173 rows x 2 columns]
                           title    weight
0                Rosewood (1997)  2.000000
1        Devil's Own, The (1997)  0.905811
2          Murder at 1600 (1997)  0.675391
3       L.A. Confidential (1997)  0.665343
4      Return of the Jedi (1983)  0.587440
5         Full Monty, The (1997)  0.537006
6               G.I. Jane (1997)  0.533060
7                   Fargo (1996)  0.395325
8            Dante's Peak (1997)  0.390000
9       Conspiracy Theory (1997)  0.385576
10                Volcano (1997)  0.370156
11             Saint, The (1997)  0.195022
12         Godfather, The (1972)  0.181719
13                  Evita (1996)  0.132949
14   English Patient, The (1996)  0.086760
15                 Scream (1996)  0.072576
16          Air Force One (1997)  0.063080
17              Star Wars (1977)  0.062899
18              Game, The (1997)  0.006120
19            Chasing Amy (1997) -0.048923
20  Devil's Advocate, The (1997) -0.055451
21                Contact (1997) -0.078921
22                Titanic (1997) -0.106322
23              Liar Liar (1997) -0.196005
                                                 title    weight
0                                     Liar Liar (1997)  4.000000
1                                Batman Forever (1995)  2.067871
2                                          Bean (1997)  2.018758
3                                     Mask, The (1994)  1.938599
4                                Down Periscope (1996)  1.890722
..                                                 ...       ...
393                                 Hoop Dreams (1994) -0.738012
394                                     Ed Wood (1994) -0.797923
395  Dr. Strangelove or: How I Learned to Stop Worr... -0.952370
396                    Welcome to the Dollhouse (1995) -1.016923
397                                 Raging Bull (1980) -1.232516

[398 rows x 2 columns]
                                                 title    weight
0                                 Air Force One (1997)  4.000000
1                     Hunt for Red October, The (1990)  2.217532
2                                   Jackal, The (1997)  2.158597
3                                     Firm, The (1993)  2.106973
4                                Murder at 1600 (1997)  2.059625
..                                                 ...       ...
286                Monty Python's Life of Brian (1979) -0.928917
287  Dr. Strangelove or: How I Learned to Stop Worr... -0.948621
288                            Mighty Aphrodite (1995) -0.957560
289                                    Fantasia (1940) -1.082525
290                       2001: A Space Odyssey (1968) -1.131976

[291 rows x 2 columns]
                                 title    weight
0             L.A. Confidential (1997)  4.000000
1    Jackie Chan's First Strike (1996)  1.842566
2                   Taxi Driver (1976)  1.781643
3                         Kolya (1996)  1.711996
4                     Chinatown (1974)  1.623745
..                                 ...       ...
218              Lion King, The (1994) -0.374754
219          Fifth Element, The (1997) -0.428814
220                  Phenomenon (1996) -0.456539
221    Clear and Present Danger (1994) -0.539125
222        Sleepless in Seattle (1993) -0.639042

[223 rows x 2 columns]
                             title    weight
0            Rainmaker, The (1997)  3.000000
1    Independence Day (ID4) (1996)  1.539282
2                 Rock, The (1996)  1.442159
3         Good Will Hunting (1997)  1.304105
4         Conspiracy Theory (1997)  1.140582
5                 Game, The (1997)  1.118906
6                Saint, The (1997)  1.067318
7            Kiss the Girls (1997)  1.041297
8             Air Force One (1997)  1.030631
9                  Cop Land (1997)  0.919650
10                  Titanic (1997)  0.916604
11           Murder at 1600 (1997)  0.880662
12                Toy Story (1995)  0.872589
13            Jerry Maguire (1996)  0.822218
14                G.I. Jane (1997)  0.810427
15         Devil's Own, The (1997)  0.795898
16             Dante's Peak (1997)  0.782439
17                  Amistad (1997)  0.714115
18                Star Wars (1977)  0.672780
19                  Contact (1997)  0.657477
20                  Volcano (1997)  0.655530
21              Chasing Amy (1997)  0.627890
22     George of the Jungle (1997)  0.617960
23  Raiders of the Lost Ark (1981)  0.594592
24     Seven Years in Tibet (1997)  0.541089
25           Godfather, The (1972)  0.524328
26                 In & Out (1997)  0.515236
27                    Evita (1996)  0.512503
28     English Patient, The (1996)  0.487592
29                    Fargo (1996)  0.484241
30                   Scream (1996)  0.431415
31                Apt Pupil (1998)  0.411663
32       Return of the Jedi (1983)  0.361041
33                  Gattaca (1997)  0.308627
34                Liar Liar (1997)  0.300279
35              Wag the Dog (1997)  0.287971
36    Devil's Advocate, The (1997)  0.218827
37      Tomorrow Never Dies (1997)  0.138035
38             Jackie Brown (1997)  0.026466
39         Dead Man Walking (1995)  0.017687
40        L.A. Confidential (1997) -0.027890
41        Starship Troopers (1997) -0.149808
42          Full Monty, The (1997) -0.178292
43             Pulp Fiction (1994) -0.613182
44            Boogie Nights (1997) -0.735801
                                title    weight
0                      Titanic (1997)  5.000000
1              River Wild, The (1994)  2.487999
2                   Abyss, The (1989)  2.360514
3                    True Lies (1994)  2.175520
4    Last of the Mohicans, The (1992)  2.136196
..                                ...       ...
261     Wings of the Dove, The (1997) -1.046152
262               Jackie Brown (1997) -1.184206
263                     Brazil (1985) -1.217658
264          Cold Comfort Farm (1995) -1.535748
265  James and the Giant Peach (1996) -1.851241

[266 rows x 2 columns]
                        title    weight
0            Apt Pupil (1998)  5.000000
1   As Good As It Gets (1997)  3.509655
2              Amistad (1997)  2.140384
3         Forrest Gump (1994)  1.812537
4   Dead Poets Society (1989)  1.713496
..                        ...       ...
61      Godfather, The (1972) -0.474936
62           Toy Story (1995) -0.520328
63        Dante's Peak (1997) -0.573545
64               Fargo (1996) -0.678207
65    Schindler's List (1993) -0.967827

[66 rows x 2 columns]
                               title    weight
0          As Good As It Gets (1997)  5.000000
1                   Apt Pupil (1998)  3.509655
2              Murder at 1600 (1997)  2.012953
3           Good Will Hunting (1997)  1.859873
4           Conspiracy Theory (1997)  1.747246
5                   Game, The (1997)  1.641467
6            Devil's Own, The (1997)  1.485521
7               Jerry Maguire (1996)  1.184623
8                 Wag the Dog (1997)  1.159343
9                    In & Out (1997)  1.118516
10       English Patient, The (1996)  1.083691
11                 Saint, The (1997)  1.078514
12                    Contact (1997)  1.069849
13                      Evita (1996)  1.060924
14        Tomorrow Never Dies (1997)  0.922809
15              Air Force One (1997)  0.869248
16                    Titanic (1997)  0.785931
17                Chasing Amy (1997)  0.736720
18                     Scream (1996)  0.666707
19             Godfather, The (1972)  0.579071
20   Empire Strikes Back, The (1980)  0.487876
21         Return of the Jedi (1983)  0.413465
22                  Rock, The (1996)  0.389645
23  Silence of the Lambs, The (1991)  0.328252
24                  Liar Liar (1997)  0.262234
25               Pulp Fiction (1994)  0.239994
26    Raiders of the Lost Ark (1981)  0.186331
27            Full Monty, The (1997) -0.096629
28          L.A. Confidential (1997) -0.387784
29          Starship Troopers (1997) -0.393906
30                      Fargo (1996) -0.503879
31                  Star Wars (1977) -0.652328
                                  title    weight
0                         Mother (1996)  1.000000
1                  Birdcage, The (1996)  0.388618
2                       Cop Land (1997)  0.275272
3                 Twelve Monkeys (1995)  0.263596
4                    Chasing Amy (1997)  0.256388
5                    Postino, Il (1994)  0.239420
6                       In & Out (1997)  0.238284
7                      Toy Story (1995)  0.225091
8                   Men in Black (1997)  0.224947
9                  Boogie Nights (1997)  0.208443
10                         Evita (1996)  0.207330
11           Princess Bride, The (1987)  0.201705
12                Godfather, The (1972)  0.190159
13                Secrets & Lies (1996)  0.165703
14                  Pulp Fiction (1994)  0.160022
15             Conspiracy Theory (1997)  0.159965
16           Usual Suspects, The (1995)  0.153700
17                     Star Wars (1977)  0.151852
18              Schindler's List (1993)  0.146918
19      Empire Strikes Back, The (1980)  0.146700
20                       Amadeus (1984)  0.142115
21                 Air Force One (1997)  0.140311
22     Silence of the Lambs, The (1991)  0.135117
23                 Fly Away Home (1996)  0.128524
24               Full Monty, The (1997)  0.120500
25                     Game, The (1997)  0.112379
26          English Patient, The (1996)  0.110412
27                 Jerry Maguire (1996)  0.110233
28             L.A. Confidential (1997)  0.106009
29            Return of the Jedi (1983)  0.099290
30                        Scream (1996)  0.098723
31         Devil's Advocate, The (1997)  0.094838
32          George of the Jungle (1997)  0.089181
33                Murder at 1600 (1997)  0.087867
34       Raiders of the Lost Ark (1981)  0.086432
35                     G.I. Jane (1997)  0.080785
36                       Contact (1997)  0.077924
37  Truth About Cats & Dogs, The (1996)  0.069849
38         Sense and Sensibility (1995)  0.068935
39                         Fargo (1996)  0.060326
40             Leaving Las Vegas (1995)  0.056549
41                     Lone Star (1996)  0.040729
42      Everyone Says I Love You (1996)  0.038994
43                  Dante's Peak (1997)  0.035919
44                       Titanic (1997)  0.032317
45              Devil's Own, The (1997)  0.031976
46      Star Trek: First Contact (1996)  0.031384
47        Independence Day (ID4) (1996)  0.029333
48                       Volcano (1997)  0.022714
49                 Fugitive, The (1993) -0.003495
50           Mission: Impossible (1996) -0.011130
51                     Liar Liar (1997) -0.017113
52                    Saint, The (1997) -0.027227
53            Mr. Holland's Opus (1995) -0.043420
54                     Rock, The (1996) -0.050498
55                 Trainspotting (1996) -0.058151
56              Dead Man Walking (1995) -0.079117
57     Shawshank Redemption, The (1994) -0.081023
58                    Braveheart (1995) -0.089713
59                   Ulee's Gold (1997) -0.099011
                                  title    weight
0                   Dante's Peak (1997)  3.000000
1                        Volcano (1997)  1.768292
2                Peacemaker, The (1997)  1.683134
3                  Jungle2Jungle (1997)  1.662672
4                      G.I. Jane (1997)  1.574771
..                                  ...       ...
136          Sound of Music, The (1965) -0.412410
137  Four Weddings and a Funeral (1994) -0.430404
138                 Forrest Gump (1994) -0.563947
139                Boogie Nights (1997) -0.596094
140            Leaving Las Vegas (1995) -0.711678

[141 rows x 2 columns]
                          title    weight
0              G.I. Jane (1997)  3.000000
1              Rock, The (1996)  1.581951
2           Dante's Peak (1997)  1.574771
3             Braveheart (1995)  1.530893
4         Kiss the Girls (1997)  1.436069
..                          ...       ...
58             Apt Pupil (1998) -0.173145
59         Boogie Nights (1997) -0.250058
60   Usual Suspects, The (1995) -0.324485
61             Star Wars (1977) -0.530202
62  George of the Jungle (1997) -0.559731

[63 rows x 2 columns]
                                   title    weight
0               Conspiracy Theory (1997)  4.000000
1                 River Wild, The (1994)  2.204538
2                          Ransom (1996)  2.112091
3                     Jackal, The (1997)  2.095716
4                    Crimson Tide (1995)  1.950255
..                                   ...       ...
212                  Lost Highway (1997) -0.768141
213              Mighty Aphrodite (1995) -0.886643
214             Leaving Las Vegas (1995) -0.940421
215                  Citizen Kane (1941) -1.105824

title
Men in Black (1997)                 2.689870
River Wild, The (1994)              2.487999
Speed (1994)                        2.371772
Abyss, The (1989)                   2.360514
Devil's Own, The (1997)             2.264297
Hunt for Red October, The (1990)    2.217532
Nell (1994)                         2.196921
True Lies (1994)                    2.175520
Seven (Se7en) (1995)                2.151834
Last of the Mohicans, The (1992)    2.136196
Name: weight, dtype: float64

In [112]:
movie_list.set_index('title', inplace=True)

AttributeError: 'Series' object has no attribute 'set_index'

In [113]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
df

In [119]:
# 코사인 유사도에 넣을 때에는 NaN을 0으로 바꾼 후에 넣는다.
values = cosine_similarity(df.transpose().fillna(0))

In [120]:
df_corr = pd.DataFrame(values, index=df.columns, columns=df.columns)

In [122]:
df_corr

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
title,,,,,,,,,,,,,,,,,,,,,
'Til There Was You (1997),1.000000,0.000000,0.024561,0.099561,0.185236,0.159265,0.000000,0.052203,0.000000,0.033326,...,0.000000,0.000000,0.000000,0.027774,0.118840,0.142315,0.029070,0.000000,0.110208,0.000000
1-900 (1994),0.000000,1.000000,0.014139,0.009294,0.007354,0.004702,0.010055,0.067038,0.000000,0.000000,...,0.152499,0.015484,0.000000,0.069284,0.018243,0.023408,0.006694,0.079640,0.042295,0.000000
101 Dalmatians (1996),0.024561,0.014139,1.000000,0.167006,0.061105,0.143878,0.203781,0.225803,0.027642,0.092337,...,0.000000,0.021965,0.030905,0.274877,0.204267,0.101199,0.056976,0.172155,0.045714,0.000000
12 Angry Men (1957),0.099561,0.009294,0.167006,1.000000,0.056822,0.167235,0.304078,0.422506,0.072682,0.394854,...,0.060946,0.016502,0.000000,0.403270,0.259436,0.145519,0.105226,0.038901,0.060101,0.081261
187 (1997),0.185236,0.007354,0.061105,0.056822,1.000000,0.132327,0.042928,0.065060,0.043133,0.027300,...,0.000000,0.141997,0.000000,0.068257,0.067786,0.091293,0.099490,0.025184,0.142667,0.096449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Young Guns II (1990),0.142315,0.023408,0.101199,0.145519,0.091293,0.225578,0.109645,0.163646,0.000000,0.074020,...,0.153493,0.000000,0.000000,0.256593,0.621260,1.000000,0.051655,0.000000,0.099333,0.000000
"Young Poisoner's Handbook, The (1995)",0.029070,0.006694,0.056976,0.105226,0.099490,0.196235,0.120116,0.155034,0.039261,0.063504,...,0.000000,0.013371,0.000000,0.133463,0.097146,0.051655,1.000000,0.022923,0.000000,0.175581
Zeus and Roxanne (1997),0.000000,0.079640,0.172155,0.038901,0.025184,0.064405,0.017218,0.026388,0.000000,0.021899,...,0.000000,0.053025,0.000000,0.054753,0.000000,0.000000,0.022923,1.000000,0.000000,0.000000
unknown,0.110208,0.042295,0.045714,0.060101,0.142667,0.042755,0.064008,0.096697,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.101775,0.058064,0.099333,0.000000,0.000000,1.000000,0.000000
Á köldum klaka (Cold Fever) (1994),0.000000,0.000000,0.000000,0.081261,0.096449,0.092494,0.000000,0.060634,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.052422,0.000000,0.000000,0.175581,0.000000,0.000000,1.000000

In [121]:
df.shape

(943, 1664)

In [61]:
my_review

    user_id                                          title  rating
0       895                               Toy Story (1995)       4
1       895                        Mighty Aphrodite (1995)       5
2       895                               Star Wars (1977)       5
3       895                                   Fargo (1996)       4
4       895                               Rock, The (1996)       3
5       895   Willy Wonka and the Chocolate Factory (1971)       5
6       895                      Return of the Jedi (1983)       5
7       895                Star Trek: First Contact (1996)       3
8       895                   Sense and Sensibility (1995)       5
9       895                                    Emma (1996)       4
10      895                                 Tin Cup (1996)       3
11      895                               Liar Liar (1997)       4
12      895                                In & Out (1997)       4
13      895                       Conspiracy Theory (1997)       4
14      895                                  Eraser (1996)       2
15      895                                  Ransom (1996)       4
16      895                              Saint, The (1997)       3
17      895                                Phantoms (1998)       2
18      895           Beautician and the Beast, The (1997)       3
19      895  Romy and Michele's High School Reunion (1997)       3

In [63]:
df_corr = df.corr(min_periods=50)

#### df_corr 이 상관계수 데이터 프레임을 가지고, 유저가 본 영화의 유사도를 측정해서
#### 추천영화를 뽑아오되, 유저가 준 별점을 반영해서 가중치를 준다.

In [75]:
title = my_review['title'][1]

In [76]:
my_review['rating'][1]

np.int64(5)

In [87]:
df_recom = (df_corr[title].dropna().sort_values(ascending=False) * my_review['rating'][1]).to_frame()

In [89]:
df_recom.columns = ['weight']

In [94]:
df_recom.reset_index(inplace=True)

                                            title    weight
0   Romy and Michele's High School Reunion (1997)  5.000000
1                            Fugitive, The (1993)  1.931571
2                                   Ransom (1996)  1.421080
3                Silence of the Lambs, The (1991)  1.302898
4                                Star Wars (1977)  1.300561
5                                Toy Story (1995)  1.245157
6    Willy Wonka and the Chocolate Factory (1971)  1.130785
7                           Twelve Monkeys (1995)  1.127006
8             Truth About Cats & Dogs, The (1996)  1.125923
9                                 Face/Off (1997)  0.976748
10                       Leaving Las Vegas (1995)  0.916826
11                     Grosse Pointe Blank (1997)  0.909903
12                        Dead Man Walking (1995)  0.884134
13                           Trainspotting (1996)  0.863285
14                                   Fargo (1996)  0.815080
15                            Men in Black (1997)  0.791371
16                                  Eraser (1996)  0.711723
17                                 Contact (1997)  0.525487
18                 Raiders of the Lost Ark (1981)  0.504434
19                  Independence Day (ID4) (1996)  0.492901
20              E.T. the Extra-Terrestrial (1982)  0.441907
21                      Return of the Jedi (1983)  0.441204
22                My Best Friend's Wedding (1997)  0.385897
23                      Back to the Future (1985)  0.367114
24                                 Twister (1996)  0.310697
25                     Mission: Impossible (1996)  0.295596
26                          Godfather, The (1972)  0.228718
27                           Birdcage, The (1996)  0.202670
28                            Forrest Gump (1994)  0.196265
29                              Saint, The (1997)  0.154619
30                Star Trek: First Contact (1996)  0.075849
31                         Time to Kill, A (1996) -0.008758
32                           Seven (Se7en) (1995) -0.027829
33                               Rock, The (1996) -0.067350
34                           Mars Attacks! (1996) -0.088979
35                               Liar Liar (1997) -0.097331
36                              Phenomenon (1996) -0.130976
37                      Mr. Holland's Opus (1995) -0.165599
38                      Fifth Element, The (1997) -0.180322
39                                  Scream (1996) -0.247855
40                           Jerry Maguire (1996) -0.272400
41                 When Harry Met Sally... (1989) -0.316929
42                            Broken Arrow (1996) -0.491211
43                            Pulp Fiction (1994) -1.121799

### 영화 1600편의 영화가 있다. 신규서버라서 회원이 천명밖에 없다
### 영화는 1600편이 있는데, 리뷰는 백명이 남겼다. 1600편 영화중에서도 유명한 영화면 리뷰를 남겼다.
### DB에 테이블은 movie, review 테이블이 있다. 영화목록이 나오도록 SQL 만들어야 한다.